import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Mail, Phone, MapPin } from "lucide-react";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { Label } from "./ui/label";
export function ContactContent() {
    return (_jsxs("div", { className: "p-6 bg-gray-800 rounded-r-xl shadow-lg flex-grow", children: [_jsx("h1", { className: "text-4xl font-bold text-white mb-6", children: "Contacto" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8", children: [_jsxs("div", { className: "space-y-6 text-gray-400", children: [_jsx("p", { className: "text-lg", children: "Estoy disponible para nuevos proyectos y colaboraciones. No dudes en enviarme un mensaje." }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Mail, { className: "w-6 h-6 text-blue-400" }), _jsx("span", { children: "tu.email@example.com" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Phone, { className: "w-6 h-6 text-blue-400" }), _jsx("span", { children: "+123 456 7890" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(MapPin, { className: "w-6 h-6 text-blue-400" }), _jsx("span", { children: "Tu Ciudad, Tu Pa\u00EDs" })] })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { htmlFor: "name", className: "text-gray-300", children: "Nombre" }), _jsx(Input, { id: "name", placeholder: "Tu Nombre", className: "bg-gray-700 border-gray-600 text-white focus:ring-blue-500" })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { htmlFor: "email", className: "text-gray-300", children: "Correo Electr\u00F3nico" }), _jsx(Input, { id: "email", type: "email", placeholder: "tu.correo@example.com", className: "bg-gray-700 border-gray-600 text-white focus:ring-blue-500" })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { htmlFor: "message", className: "text-gray-300", children: "Mensaje" }), _jsx(Textarea, { id: "message", placeholder: "Tu mensaje...", rows: 5, className: "bg-gray-700 border-gray-600 text-white focus:ring-blue-500" })] }), _jsx(Button, { className: "w-full bg-blue-600 hover:bg-blue-700 text-white", children: "Enviar Mensaje" })] })] })] }));
}
